;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; SNIFFER_SETTINGS
;
; SNIFFER_TYPE : 0 or 1
; CHANNEL_INDEX
; =============
; Channel Index value 37,38 and 39
; Channel in which sniffer want to listen for BLE_Packet.
;
; TI_BLE_PORT= <Valid Port> (Default Port - 5000)
; Eg:
; ==
; BLE_DEVICE= 0 or 1 (Default 0)
;   0 - CC1350
;   1 - CC2650
; CHANNEL_INDEX=37
; TI_BLE_PORT = 5000
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[SNIFFER_SETTINGS]
GET_DEVICEID_FROM_RESPONSE = 0
ALLOW_ALL_UUID = 1
BLE_DEVICE_TYPE = G4 EM, IF-TAG, EM-TAG, DT-TAG, CENLOC, UV 63
ENABLE_RSSI_THRESHOLD=1
TI_BLE_PORT=5000
BLE_DEVICE=1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; RSSI_SETTINGS
; 
; MIN_RSSI = <Minimum Rssi threshold>
; MAX_RSSI = <Maximum Rssi threshold>
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[RSSI_SETTINGS]
MIN_RSSI=-90.0
MAX_RSSI=-40.0


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[BLE_DEVICE_UUID]
COUNT = 1
BLE_UUID1 = 01020304
