;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [SETTINGS]
;
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[SETTINGS]
KEITHELY_VISA_RESOURCE_NAME = USB0::0x05E6::0x2110::1421034::INSTR
KEITHELY_DATA_SAMPLE_COUNT = 5
COMM_PORT = 5

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [RF_TRANSMISSION_TEST]
;
; TX_POWER = Value (1 = -10dbm, 2 = 0dbm, 3 = 1dbm, 4 = 2dbm, 5 = 3dbm, 6 = 4dbm, 
;                   7 = 5dbm, 8 = 6dbm, 9 = 7dbm, 10 = 8dbm, 11 = 9dbm, 12 = 10dbm, 
;                   13 = 11dbm, 14 = 12dbm, 15 = 14dbm )
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[RF_TRANSMISSION_TEST]
NAME = RF Transmission Test
ALLOWD_FREQ = 914.020
ALLOWED_OFFSET = 10
TX_FREQ = 1
TX_POWER = 12
TIMEOUT = 1000
RETRY = 3
ENABLE_TEST = 1
ENABLE_CALIBRATION = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [RF_SENSITIVITY_TEST]
;
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[RF_SENSITIVITY_TEST]
NAME = RF Sensitivity Test
RX_FREQ = 1
LOW_RSSI_RANGE = -79
HIGH_RSSI_RANGE = -50
TIMEOUT = 1000
RETRY = 3
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [VOLTAGE_TEST]
;
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[VOLTAGE_TEST]
NAME = Battery Voltage Test
MIN_VOLTAGE = 3.15 
MAX_VOLTAGE = 3.40 
TIMEOUT = 1000
RETRY = 3
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [BLE_TX_TEST]
;  TX_POWER = Value( 0 = -20 dbm, 1 = - 18 dbm, 2 = -15 dbm, 3 = -12 dbm, 4 = -10 dbm, 
		     5 = -9 dbm, 6 = -6 dbm, 7 = -5 dbm, 8 = -3 dbm, 
;                    9 = 0, 10 = 1, 11 = 2, 12 = 3, 13 = 4, 14 = 5 )
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[BLE_TX_TEST]
NAME = BLE Tx Test
TIMEOUT = 3000
RETRY = 3
PORT = 7000
ENABLE_TEST = 1
TX_POWER = 14
COUNT = 2

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [ACCELEROMETER_TEST]
;
; SNIFFER_RATE => 1 : 0.4 HZ, 2 : 0.8 HZ, 3 : 1.5 HZ, 4 : 7 HZ, 5 : 14 HZ, 6 : 28, 7 : 54 HZ, 8: 105 HZ, 9 : 210 HZ, 10 : 400 HZ, 11 : 600 HZ
; SNIFFER_COUNT = 0 to 63
; ACCEL_RESOLUTIONS = 0 5; 0 - 6 bits, 1 - 7 bits, 2 - 8 bits, 3 - 10 bits, 4 - 12 bits,  5 - 14 bits (only 12-bits if FIFO enabled)
; ACCEL_RANGE = 0 - 4; 0 - ±2g, 1 - ±4g, 2 - ±8g, 3 - ±16g, 4 - ±12g
; SAMPLE_RATE or CWAKE Rate = 5 to 11; 5 - 14 Hz, 6 - 28 Hz, 7 - 54 Hz, 8 - 105 Hz, 9 - 210 Hz, 10 - 400 Hz,11 - 600 Hz
; SNIFFER_THRESHOLD = 0 to 63 
; TAG_TEST_TIMEOUT = 2 Default 1 sec; Timeout in 500 ms
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[ACCELEROMETER_TEST]
NAME = Motion Trigger Test
TIMEOUT = 1000
RETRY = 3
ENABLE_TEST = 1

X_G_RANGE_FROM = -10.0
X_G_RANGE_TO = 10.0

Y_G_RANGE_FROM = -10.0
Y_G_RANGE_TO = 10.0

Z_G_RANGE_FROM = -10.0
Z_G_RANGE_TO = 10.0

AXIS_TEST = 0

ACCEL_RANGE = 0
ACCEL_RESOLUTIONS = 0
SNIFFER_RATE = 7
SAMPLE_RATE = 7
SNIFFER_COUNT = 3
SNIFFER_THRESHOLD = 3
TAG_TEST_TIMEOUT = 4

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [BUZZER_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[BUZZER_TEST]
NAME = Buzzer Test
MIN_CURRENT = 8.80 ;;mA
MAX_CURRENT = 11.05 ;;mA
TIMEOUT = 1000
RETRY = 3
ENABLE_TEST = 1
BUZZER_FREQ = 4.5

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [FLASH_MEMORY_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[FLASH_MEMORY_TEST]
NAME = Flash Memory Test
TIMEOUT = 500
RETRY = 3
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [LF_CALIBRATION__CHANNLE1_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[LF_CALIBRATION__CHANNLE1_TEST]
NAME = LF calibration channel 1 Test
TIMEOUT = 1000
RETRY = 3
ENABLE_TEST = 1
LF_CLOCK = 125
USE_LF_CALIBRATION = 0
MIN_LF_ALLOWED_COUNT = 997
MAX_LF_ALLOWED_COUNT = 1003

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [LF_CALIBRATION__CHANNLE3_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[LF_CALIBRATION__CHANNLE3_TEST]
NAME = LF calibration channel 3 Test
TIMEOUT = 1000
RETRY = 3
ENABLE_TEST = 1
LF_CLOCK = 125
USE_LF_CALIBRATION = 0
MIN_LF_ALLOWED_COUNT = 997
MAX_LF_ALLOWED_COUNT = 1003

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [LF_RX_CHANNLE1_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[LF_RX_CHANNLE1_TEST]
NAME = LF RX Channel 1 Test
LF_ID = 2272
TIMEOUT = 3000
RETRY = 1
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [LF_RX_CHANNLE3_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[LF_RX_CHANNLE3_TEST]
NAME = LF RX Channel 3 Test
LF_ID = 2272
TIMEOUT = 3000
RETRY = 1
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [IR_RXA_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[IR_RXA_TEST]
NAME = IR RX A Test
IR_ID = 2232
TIMEOUT = 6000
RETRY = 1
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [IR_RXB_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[IR_RXB_TEST]
NAME = IR RX B Test
IR_ID = 2232
TIMEOUT = 6000
RETRY = 1
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [LED1_TEST]
;
; 7 - 1 mA
; 79 - 10 mA
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[LED1_TEST]
NAME = Led 1 Test
MIN_CURRENT = 1.00 ;;mA
MAX_CURRENT = 1.75 ;;mA
TIMEOUT = 500
RETRY = 3
ENABLE_TEST = 1
LED_OUT_CURRENT = 7 

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [LED2_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[LED2_TEST]
NAME = Led 2 Test
MIN_CURRENT = 1.00 ;;mA
MAX_CURRENT = 1.75 ;;mA
TIMEOUT = 500
RETRY = 3
ENABLE_TEST = 1
LED_OUT_CURRENT = 7

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [LED3_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[LED3_TEST]
NAME = Led 3 Test
MIN_CURRENT = 1.00 ;;mA
MAX_CURRENT = 1.75 ;;mA
TIMEOUT = 500
RETRY = 3
ENABLE_TEST = 1
LED_OUT_CURRENT = 7

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [LED4_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[LED4_TEST]
MIN_CURRENT = 1.00 ;;mA
MAX_CURRENT = 1.75 ;;mA
TIMEOUT = 500
RETRY = 3
ENABLE_TEST = 1
LED_OUT_CURRENT = 7

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [RED_LED_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[RED_LED_TEST]
NAME = Red Led Test
MIN_CURRENT = 3.00 ;;mA
MAX_CURRENT = 3.90 ;;mA
TIMEOUT = 1000
RETRY = 3
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [BUTTON_1_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[BUTTON_1_TEST]
NAME = Button 1 Test
KEY_VALUE = 1
TIMEOUT = 5000
RETRY = 3
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [BUTTON_2_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[BUTTON_2_TEST]
NAME = Button 2 Test
KEY_VALUE = 2
TIMEOUT = 5000
RETRY = 3
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [BUTTON_3_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[BUTTON_3_TEST]
NAME = Button 3 Test
KEY_VALUE = 3
TIMEOUT = 5000
RETRY = 3
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [MOTION_TEST]
;
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[MOTION_TEST]
NAME = Motion Test
TIMEOUT = 3000
RETRY = 3
ENABLE_TEST = 0

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [PROXIMITY_TEST]
;
;
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[PROXIMITY_TEST]
NAME = Proximity Test
MIN_PROXI_RANGE = 6000
MAX_PROXI_RANGE = 8000
TIMEOUT = 1000
RETRY = 3
ENABLE_TEST = 0

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [SLEEP_CURRENT_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[SLEEP_CURRENT_TEST]
NAME = Sleep Current Test
MIN_CURRENT = 3 ;;uA
MAX_CURRENT = 12;;uA
TIMEOUT = 1000
RETRY = 3
ENABLE_TEST = 1
SLEEP_TIME = 3 ;;sec
DELAY_BEFORE_MEASUREMENT = 1000
MEASUREMENT_DELAY = 1000

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [250MS_CLOCK_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[250MS_CLOCK_TEST]
NAME = 250 ms Clock Test
TIMEOUT = 5000
RETRY = 1
ENABLE_TEST = 1
CLOCK_COUNT = 4

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [FACTORY_PARAM]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[FACTORY_PARAM]
NAME = Get Factory Param
TIMEOUT = 1000
RETRY = 3
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [32KHZ_CLOCK_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[32KHZ_CLOCK_TEST]
NAME = 32 kHz Clock Test
TIMEOUT = 5000
RETRY = 3
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [FACTORY_SLEEP_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[FACTORY_SLEEP_TEST]
NAME = Factory Sleep
TIMEOUT = 500
RETRY = 1
ENABLE_TEST = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [16MHZ_CLOCK_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[16MHZ_CLOCK_TEST]
NAME = 16 MHz Clock Test
TIMEOUT = 1000
RETRY = 1
ENABLE_TEST = 1
    
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; [LF_RC_CLOCK_TEST]
;
; 
; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[LF_RC_CLOCK_TEST]
NAME = LF Clock Test
TIMEOUT = 1000
RETRY = 1
ENABLE_TEST = 1